# Generated by Django 5.2 on 2025-05-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patron',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
