# Generated by Django 5.2 on 2025-05-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrones', '0002_rename_titulo_patron_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
