# Generated by Django 5.2 on 2025-05-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil'),
        ),
    ]
