# Generated by Django 5.2 on 2025-05-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotos_perfil'),
        ),
    ]
